version: '3.8'

services:
  # PostgreSQL + TimescaleDB for time-series data
  postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: v26meme_db
    environment:
      POSTGRES_DB: v26meme
      POSTGRES_USER: v26meme
      POSTGRES_PASSWORD: v26meme_secure_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U v26meme"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching and real-time data
  redis:
    image: redis:7-alpine
    container_name: v26meme_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:
